server:
  port: 8080

vertx:
  websocket:
    port: 8081

spring:
  application:
    name: vertx-akka-springboot-game

akka:
  cluster:
    port: 10001 # 默认端口，可以通过-Dakka.cluster.port=xxx覆盖
    roles: ["game-node"]

logging:
  level:
    com.sirius.game: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"