server:
  port: 8080

vertx:
  websocket:
    port: 8081

spring:
  application:
    name: vertx-akka-springboot-game

logging:
  level:
    com.sirius.game: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"